### PR TITLE
Print when the Dynamo process exits

### PR DESCRIPTION
**Pull request by arohner**
Adds a simple log line when the dynamo process exits.

### CODE REVIEW

**Comment by dmcgillen** [comment]
I think this should be added to the existing shutdown hook in clean-up-on-shutdown rather than having another function. What do you reckon?

**Comment by arohner** [comment]
I could go either way. I don't have a problem moving monitor inside clean-up-on-shutdown, but then, IMO, the name should change. Any suggestions?

**Comment by dmcgillen** [comment]
Sorry about the delay. I think I prefer it in the same function as it's all part of the shutdown process. Maybe that function could be called handle-shutdown?

**Comment by dmcgillen** [comment]
Just chucked it in seen as it was a one liner: https://github.com/dmcgillen/lein-dynamodb-local/commit/6fd89d39452cb5099b70ff1eaaf793a8319bd168

**Pull request closed without merging**
